# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "activerecord-model-spaces"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mccraig mccraig of the clan mccraig"]
  s.date = "2013-01-30"
  s.description = "map activerecord models to tables depending on context"
  s.email = "mccraigmccraig@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "activerecord-model-spaces.gemspec",
    "lib/active_record/model_spaces.rb",
    "lib/active_record/model_spaces/context.rb",
    "lib/active_record/model_spaces/model_space.rb",
    "lib/active_record/model_spaces/persistor.rb",
    "lib/active_record/model_spaces/registry.rb",
    "lib/active_record/model_spaces/table_manager.rb",
    "lib/active_record/model_spaces/table_names.rb",
    "lib/active_record/model_spaces/util.rb",
    "spec/active_record/model_spaces/context_spec.rb",
    "spec/active_record/model_spaces/model_space_spec.rb",
    "spec/active_record/model_spaces/persistor_spec.rb",
    "spec/active_record/model_spaces/registry_spec.rb",
    "spec/active_record/model_spaces/table_manager_spec.rb",
    "spec/active_record/model_spaces/table_names_spec.rb",
    "spec/active_record/model_spaces/util_spec.rb",
    "spec/active_record/model_spaces_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/mccraigmccraig/activerecord-model-spaces"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "manage activerecord model to table mappings"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.8.7"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<activerecord>, [">= 2.3.0"])
      s.add_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<activerecord>, [">= 2.3.0"])
    s.add_dependency(%q<rspec>, ["~> 2.12.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

